apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-velero-operator
  namespace: openshift-velero
  labels:
    name: managed-velero-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: managed-velero-operator
  template:
    metadata:
      labels:
        name: managed-velero-operator
    spec:
      serviceAccountName: managed-velero-operator
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
            weight: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
      containers:
        - name: managed-velero-operator
          image: quay.io/openshift-sre/managed-velero-operator
          command:
          - managed-velero-operator
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              memory: "500Mi"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "managed-velero-operator"
